[build]
  base    = "class-site"
  publish = "."
  ignore  = "BACKUPS/, testing-framework/, docs/, scripts/, config/, referance/, class-site/docs/, class-site/local-dev-config.js, class-site/env.example, class-site/environment.txt, class-site/local-dev-config.example.js, class-site/node_modules/, class-site/package.json, class-site/package-lock.json, class-site/ROLLBACK_GUIDE.md"

# 환경변수 설정
[build.environment]
  ADMIN_PASSWORD = "2025sapa"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# CORS 및 헤더 설정
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Submission-Key, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Credentials = "true"

# Edge Functions routing for session2 gate
[[edge_functions]]
path = "/science-experiments/suhaeng3/session2"
function = "gate-session2"

[[edge_functions]]
path = "/science-experiments/suhaeng3/session2.html"
function = "gate-session2"

[[edge_functions]]
path = "/science-experiments/suhaeng3/session2/*"
function = "gate-session2"

# Edge Functions routing for suhaeng4 gate
[[edge_functions]]
path = "/science-experiments/suhaeng4"
function = "gate-suhaeng4"

[[edge_functions]]
path = "/science-experiments/suhaeng4/"
function = "gate-suhaeng4"

[[edge_functions]]
path = "/science-experiments/suhaeng4/*"
function = "gate-suhaeng4"

# Test functions are automatically available at /.netlify/functions/
# No redirect rules needed for internal Netlify function paths

# Reduce caching to ensure timely UI updates around release window
[[headers]]
for = "/science-experiments/suhaeng3/index.html"
  [headers.values]
  Cache-Control = "no-store"

[[headers]]
for = "/science-experiments/suhaeng3/session2.html"
  [headers.values]
  Cache-Control = "no-store"
