const { spawn } = require('child_process');
const axios = require('axios');
const fs = require('fs');
const path = require('path');

const SERVER_PORT = 3000;
const BASE_URL = `http://localhost:${SERVER_PORT}`;
const SUBMIT_KEY = 'S-2025-github2025subject'; // Must match .env or server.js default

async function delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function runTests() {
    console.log('--- Server Verification Script ---');

    // 1. Check Prerequisites
    console.log('\n[1] Checking Prerequisites...');
    
    // Check tokens.json
    if (fs.existsSync('tokens.json')) {
        console.log('✅ tokens.json found.');
    } else {
        console.log('⚠️  tokens.json NOT found. OneDrive upload will fail, but PDF generation can be tested.');
    }

    // Check node_modules
    if (fs.existsSync('node_modules')) {
        console.log('✅ node_modules found.');
    } else {
        console.error('❌ node_modules NOT found. Please run "npm install" first.');
        return;
    }

    // 2. Start Server
    console.log('\n[2] Starting Server...');
    const serverProcess = spawn('node', ['server.js'], {
        cwd: __dirname,
        stdio: 'pipe', // Capture output
        shell: true
    });

    let serverStarted = false;

    const logStream = fs.createWriteStream('server.log', { flags: 'w' });

    serverProcess.stdout.on('data', (data) => {
        const output = data.toString();
        logStream.write(`[STDOUT] ${output}`);
        console.log(`[Server Log] ${output.trim()}`);
        if (output.includes(`Server running on port ${SERVER_PORT}`)) {
            serverStarted = true;
        }
    });

    serverProcess.stderr.on('data', (data) => {
        const output = data.toString();
        logStream.write(`[STDERR] ${output}`);
        console.error(`[Server Error] ${output.trim()}`);
    });

    // Wait for server to start
    console.log('Waiting for server to start...');
    let attempts = 0;
    while (!serverStarted && attempts < 10) {
        await delay(1000);
        attempts++;
    }

    if (!serverStarted) {
        console.error('❌ Server failed to start within 10 seconds.');
        serverProcess.kill();
        return;
    }
    console.log('✅ Server is running.');

    try {
        // 3. Health Check
        console.log('\n[3] Testing Health Check Endpoint (GET /)...');
        try {
            const res = await axios.get(BASE_URL);
            if (res.status === 200 && res.data.includes('running')) {
                console.log('✅ Health Check Passed:', res.data);
            } else {
                console.error('❌ Health Check Failed:', res.status, res.data);
            }
        } catch (err) {
            console.error('❌ Health Check Error:', err.message);
        }

        // 4. Submission Test
        console.log('\n[4] Testing Submission Endpoint (POST /submit)...');
        
        const mockPayload = {
            apiKey: SUBMIT_KEY,
            htmlContent: '<h1>Test Report</h1><p>This is a test submission generated by the verification script.</p>',
            studentInfo: {
                grade: '1',
                class: '1',
                number: '1',
                name: '테스트학생'
            },
            subject: 'TestSubject',
            activity: 'TestActivity'
        };

        try {
            console.log('Sending test submission...');
            const res = await axios.post(`${BASE_URL}/submit`, mockPayload);
            console.log('✅ Submission Response:', res.status, res.data);
        } catch (err) {
            if (err.response) {
                console.error('❌ Submission Failed with Status:', err.response.status);
                console.error('   Response Data:', err.response.data);
                
                // Analyze specific errors
                if (err.response.data.details && err.response.data.details.includes('No tokens found')) {
                    console.log('⚠️  Expected Error: OneDrive tokens are missing. PDF generation likely succeeded, but upload failed.');
                }
            } else {
                console.error('❌ Submission Error (Network/Server):', err.message);
            }
        }

    } catch (err) {
        console.error('Unexpected Error during tests:', err);
    } finally {
        // 5. Cleanup
        console.log('\n[5] Stopping Server...');
        serverProcess.kill();
        // On Windows, sometimes child_process.kill() doesn't kill the whole tree.
        // We might need taskkill if it persists, but for a quick test this is usually okay.
        process.exit(0);
    }
}

runTests();
